# 서버포트번호
server:
  port: 8080

spring:
  application:
    name: linco

  # ThymeLeaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  # security 설정
  security:
    #      user:
    #        name: user
    #        password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: ${rds.googleid}
            client-secret: ${rds.googlesecret}
            scope:
              - email
              - profile

          naver:
            client-id: ${rds.naverid}
            client-secret: ${rds.naversecret}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${rds.naveruri}

          kakao:
            client-id: ${rds.kakaoid}
            client-secret: ""  # 카카오는 client-secret을 사용하지 않음
            scope:
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${rds.kakakouri}


        # provider 제공
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  pagination:
    write_pages: 5
    page_rows: 15

  upload:
    path: upload

  oauth2:
    password: 1234

openapi:
  url: http://openapi.seoul.go.kr:8088/${rds.openapikey}/json/ListPublicReservationInstitution/1/520/

imp:
  client:
    code: ${rds.impcode}

  api:
    key: ${rds.impapikey}
    secretkey: ${rds.impapisecretkey}